/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.afrisoftech.hospinventory;

import com.afrisoftech.dbadmin.TableModel;
import com.afrisoftech.dbadmin.JTable;
import com.afrisoftech.hospinventory.mtrhreports.TenderEvaluationSummaryPDF;
import com.afrisoftech.lib.ClearTable;
import com.afrisoftech.lib.CurrencyFormatter;
import com.afrisoftech.lib.DBAllObjects;
import com.afrisoftech.lib.DBObject;
import com.afrisoftech.lib.GetItemInfo;
import com.afrisoftech.lib.TableColumnTotal;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.lang.model.element.Element;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author saleem
 */
public class SSOFInancialEvaluationIntfr extends javax.swing.JInternalFrame {

    /**
     * Creates new form SSOFInancialEvaluationIntfr
     */
    java.sql.Connection connectDB = null;  
    org.netbeans.lib.sql.pool.PooledConnectionSource pConnDB = null;
   private  String evaluation_dtls=null;
    public SSOFInancialEvaluationIntfr(java.sql.Connection connDb, org.netbeans.lib.sql.pool.PooledConnectionSource pconnDB) {
        connectDB = connDb;
        
        pConnDB = pconnDB;
        initComponents();
        
        
//        thresholdspinner.setValue(100);
      
        
        
        
//        thresholdspinner.setValue(thresholdspinner.getMaximumSize());
        //jSplitPane1.setDividerLocation(500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        searchtender3 = new javax.swing.JDialog();
        tenderrecordspnl3 = new javax.swing.JPanel();
        tenderrecordstxt3 = new javax.swing.JTextField();
        tenderrecordsspnl3 = new javax.swing.JScrollPane();
        tenderrecordstbl3 = new com.afrisoftech.dbadmin.JTable();
        closebtn8 = new javax.swing.JButton();
        searchtenderc = new javax.swing.JDialog();
        tenderrecordspnl4 = new javax.swing.JPanel();
        tenderrecordstxt4 = new javax.swing.JTextField();
        tenderrecordsspnl4 = new javax.swing.JScrollPane();
        tenderrecordstbl4 = new com.afrisoftech.dbadmin.JTable();
        closebtn10 = new javax.swing.JButton();
        searchsupplierc = new javax.swing.JDialog();
        searchsupplierpnl5 = new javax.swing.JPanel();
        searchsuppliertxt5 = new javax.swing.JTextField();
        searchsupplierspnl5 = new javax.swing.JScrollPane();
        searchsupplierstbl5 = new com.afrisoftech.dbadmin.JTable();
        closebtn11 = new javax.swing.JButton();
        tableBtnGroup = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        financialEvaluation = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        sortCmbx = new javax.swing.JComboBox();
        jPanel21 = new javax.swing.JPanel();
        tenderNoTxt = new javax.swing.JTextField();
        searchButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        finYrTxt = new javax.swing.JTextField();
        userNameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        agendaTxt = new javax.swing.JTextField();
        techrptbtn = new javax.swing.JButton();
        prelRptbtn = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        itemsQuotedTbl = new com.afrisoftech.dbadmin.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTbl = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        totalSelected = new javax.swing.JTextField();
        thresholdspinner = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        sort1btn = new javax.swing.JButton();
        sort2btn = new javax.swing.JButton();
        contract_management = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable5 = new com.afrisoftech.dbadmin.JTable();
        jPanel51 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel59 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton22 = new javax.swing.JButton();
        jPanel60 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jButton23 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel55 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        datePicker5 = new com.afrisoftech.lib.DatePicker();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        datePicker6 = new com.afrisoftech.lib.DatePicker();
        jLabel24 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();

        searchtender3.setModal(true);
        searchtender3.setUndecorated(true);
        searchtender3.getContentPane().setLayout(new java.awt.GridBagLayout());

        tenderrecordspnl3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tenderrecordspnl3.setLayout(new java.awt.GridBagLayout());

        tenderrecordstxt3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tenderrecordstxt3CaretUpdate(evt);
            }
        });
        tenderrecordstxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenderrecordstxt3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 300.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        tenderrecordspnl3.add(tenderrecordstxt3, gridBagConstraints);

        tenderrecordstbl3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tenderrecordstbl3.setToolTipText("Click on the target row to select the patient from the search.");
        tenderrecordstbl3.setShowHorizontalLines(false);
        /*javax.swing.table.TableColumn column = null;

        for (int i = 0; i < 4; i++) {

            column = jSearchTable.getColumnModel().getColumn(i);

            if (i == 1) {

                column.setPreferredWidth(400);
                //sport column is bigger
            } else {

                column.setPreferredWidth(200);

            }
        }
        */
        tenderrecordstbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenderrecordstbl3MouseClicked(evt);
            }
        });
        tenderrecordsspnl3.setViewportView(tenderrecordstbl3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 20.0;
        tenderrecordspnl3.add(tenderrecordsspnl3, gridBagConstraints);

        closebtn8.setText("Close");
        closebtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtn8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        tenderrecordspnl3.add(closebtn8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        searchtender3.getContentPane().add(tenderrecordspnl3, gridBagConstraints);

        searchtenderc.setModal(true);
        searchtenderc.setUndecorated(true);
        searchtenderc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchtendercFocusLost(evt);
            }
        });
        searchtenderc.getContentPane().setLayout(new java.awt.GridBagLayout());

        tenderrecordspnl4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tenderrecordspnl4.setLayout(new java.awt.GridBagLayout());

        tenderrecordstxt4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tenderrecordstxt4CaretUpdate(evt);
            }
        });
        tenderrecordstxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenderrecordstxt4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 300.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        tenderrecordspnl4.add(tenderrecordstxt4, gridBagConstraints);

        tenderrecordstbl4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tenderrecordstbl4.setToolTipText("Click on the target row to select the patient from the search.");
        tenderrecordstbl4.setShowHorizontalLines(false);
        /*javax.swing.table.TableColumn column = null;

        for (int i = 0; i < 4; i++) {

            column = jSearchTable.getColumnModel().getColumn(i);

            if (i == 1) {

                column.setPreferredWidth(400);
                //sport column is bigger
            } else {

                column.setPreferredWidth(200);

            }
        }
        */
        tenderrecordstbl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenderrecordstbl4MouseClicked(evt);
            }
        });
        tenderrecordsspnl4.setViewportView(tenderrecordstbl4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 20.0;
        tenderrecordspnl4.add(tenderrecordsspnl4, gridBagConstraints);

        closebtn10.setText("Close");
        closebtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtn10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        tenderrecordspnl4.add(closebtn10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        searchtenderc.getContentPane().add(tenderrecordspnl4, gridBagConstraints);

        searchsupplierc.setModal(false);
        searchsupplierc.setUndecorated(true);
        searchsupplierc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchsuppliercFocusLost(evt);
            }
        });
        searchsupplierc.getContentPane().setLayout(new java.awt.GridBagLayout());

        searchsupplierpnl5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchsupplierpnl5.setLayout(new java.awt.GridBagLayout());

        searchsuppliertxt5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                searchsuppliertxt5CaretUpdate(evt);
            }
        });
        searchsuppliertxt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchsuppliertxt5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 300.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        searchsupplierpnl5.add(searchsuppliertxt5, gridBagConstraints);

        searchsupplierstbl5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        searchsupplierstbl5.setToolTipText("Click on the target row to select the patient from the search.");
        searchsupplierstbl5.setShowHorizontalLines(false);
        /*javax.swing.table.TableColumn column = null;

        for (int i = 0; i < 4; i++) {

            column = jSearchTable.getColumnModel().getColumn(i);

            if (i == 1) {

                column.setPreferredWidth(400);
                //sport column is bigger
            } else {

                column.setPreferredWidth(200);

            }
        }
        */
        searchsupplierstbl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchsupplierstbl5MouseClicked(evt);
            }
        });
        searchsupplierspnl5.setViewportView(searchsupplierstbl5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 20.0;
        searchsupplierpnl5.add(searchsupplierspnl5, gridBagConstraints);

        closebtn11.setText("Close");
        closebtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtn11ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        searchsupplierpnl5.add(closebtn11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        searchsupplierc.getContentPane().add(searchsupplierpnl5, gridBagConstraints);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Financial Evaluation, Award & Contract");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jTabbedPane3.setBackground(new java.awt.Color(0, 255, 255));
        jTabbedPane3.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        financialEvaluation.setLayout(new java.awt.GridBagLayout());

        jPanel54.setLayout(new java.awt.GridBagLayout());

        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setDividerSize(5);

        jPanel19.setLayout(new java.awt.GridBagLayout());

        jPanel20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.setLayout(new java.awt.GridBagLayout());

        jLabel18.setText("Tender No:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 30);
        jPanel20.add(jLabel18, gridBagConstraints);

        jLabel19.setText("Sort By");
        jLabel19.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 30);
        jPanel20.add(jLabel19, gridBagConstraints);

        sortCmbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Lowest Price", "Highest Price" }));
        sortCmbx.setEnabled(false);
        sortCmbx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sortCmbxItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel20.add(sortCmbx, gridBagConstraints);

        jPanel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel21.setMinimumSize(new java.awt.Dimension(82, 37));
        jPanel21.setLayout(new java.awt.GridBagLayout());

        tenderNoTxt.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel21.add(tenderNoTxt, gridBagConstraints);

        searchButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kiwi/images/date.gif"))); // NOI18N
        searchButton5.setToolTipText("Search Patient's Name");
        searchButton5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        searchButton5.setMaximumSize(new java.awt.Dimension(74, 53));
        searchButton5.setMinimumSize(new java.awt.Dimension(74, 53));
        searchButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        searchButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel21.add(searchButton5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel20.add(jPanel21, gridBagConstraints);

        jLabel3.setText("Financial Year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel20.add(jLabel3, gridBagConstraints);

        jLabel4.setText("UserName");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel20.add(jLabel4, gridBagConstraints);

        finYrTxt.setEditable(false);
        finYrTxt.setText(com.afrisoftech.lib.FinancialYear.getActiveFinancialYear(connectDB));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel20.add(finYrTxt, gridBagConstraints);

        userNameTxt.setEditable(false);
        userNameTxt.setText(com.afrisoftech.lib.UserName.getLoginName(connectDB).toLowerCase());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel20.add(userNameTxt, gridBagConstraints);

        jLabel1.setText("Agenda Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel20.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel20.add(agendaTxt, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel19.add(jPanel20, gridBagConstraints);

        techrptbtn.setBackground(new java.awt.Color(204, 255, 204));
        techrptbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32x32/pdf1.jpg"))); // NOI18N
        techrptbtn.setText("Print Technical Evaluation Report");
        techrptbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        techrptbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        techrptbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        techrptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                techrptbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 5.0;
        jPanel19.add(techrptbtn, gridBagConstraints);

        prelRptbtn.setBackground(new java.awt.Color(204, 255, 204));
        prelRptbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/32x32/pdf1.jpg"))); // NOI18N
        prelRptbtn.setText("Print Preliminary Evaluation Report");
        prelRptbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        prelRptbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        prelRptbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        prelRptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prelRptbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 5.0;
        jPanel19.add(prelRptbtn, gridBagConstraints);

        jSplitPane1.setLeftComponent(jPanel19);

        jPanel24.setBackground(new java.awt.Color(204, 255, 255));
        jPanel24.setLayout(new java.awt.GridBagLayout());

        jScrollPane6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Price Schedule Per Item(Set Qty and remarks Before Selecting Award checkbox)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N

        itemsQuotedTbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        itemsQuotedTbl.setForeground(new java.awt.Color(0, 0, 204));
        itemsQuotedTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        itemsQuotedTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemsQuotedTblMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(itemsQuotedTbl);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        jPanel24.add(jScrollPane6, gridBagConstraints);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Item(s) On Tender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N

        itemTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Select Item", "Item Code", "Item Description", "Units", "Tender Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemTbl.setGridColor(new java.awt.Color(0, 0, 204));
        itemTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(itemTbl);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        jPanel24.add(jScrollPane1, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel24.add(jLabel5, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setMnemonic('m');
        jButton1.setText("        Save         ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        jPanel24.add(jButton1, gridBagConstraints);

        totalSelected.setEditable(false);
        totalSelected.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalSelected.setForeground(new java.awt.Color(255, 0, 102));
        totalSelected.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalSelected.setText("0.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel24.add(totalSelected, gridBagConstraints);

        thresholdspinner.setModel(new javax.swing.SpinnerNumberModel(100, 1, 100, 1));
        thresholdspinner.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Threshold For Technical "));
        thresholdspinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                thresholdspinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 200, 0, 100);
        jPanel24.add(thresholdspinner, gridBagConstraints);

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setText("Print Evaluation Summary");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        jPanel24.add(jButton3, gridBagConstraints);

        sort1btn.setText("A-Z");
        sort1btn.setEnabled(false);
        sort1btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort1btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel24.add(sort1btn, gridBagConstraints);

        sort2btn.setText("Z-A");
        sort2btn.setEnabled(false);
        sort2btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort2btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel24.add(sort2btn, gridBagConstraints);

        jSplitPane1.setRightComponent(jPanel24);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel54.add(jSplitPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        financialEvaluation.add(jPanel54, gridBagConstraints);

        jTabbedPane3.addTab("Financial Evaluation/Award", financialEvaluation);

        contract_management.setLayout(new java.awt.GridBagLayout());

        jScrollPane14.setBorder(javax.swing.BorderFactory.createTitledBorder("MileStones Management"));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Description", "Quantity ", "Units", "Delivery Phases", "First Delivery Date"
            }
        ));
        jScrollPane14.setViewportView(jTable5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 8.0;
        contract_management.add(jScrollPane14, gridBagConstraints);

        jPanel51.setLayout(new java.awt.GridBagLayout());

        jLabel49.setText("Tender Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel51.add(jLabel49, gridBagConstraints);

        jLabel46.setText("Supplier Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel51.add(jLabel46, gridBagConstraints);

        jPanel59.setLayout(new java.awt.GridBagLayout());

        jTextField3.setEditable(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel59.add(jTextField3, gridBagConstraints);

        jButton22.setEnabled(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel59.add(jButton22, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel51.add(jPanel59, gridBagConstraints);

        jPanel60.setLayout(new java.awt.GridBagLayout());

        jTextField6.setEditable(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel60.add(jTextField6, gridBagConstraints);

        jButton23.setEnabled(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel60.add(jButton23, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        jPanel51.add(jPanel60, gridBagConstraints);

        jLabel47.setText("Bid Amount(Kshs)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1.0;
        jPanel51.add(jLabel47, gridBagConstraints);

        jTextField7.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 1.0;
        jPanel51.add(jTextField7, gridBagConstraints);

        jLabel50.setText("Performance Bond Amt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weighty = 1.0;
        jPanel51.add(jLabel50, gridBagConstraints);

        jTextField9.setForeground(new java.awt.Color(255, 0, 0));
        jTextField9.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField9CaretUpdate(evt);
            }
        });
        jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField9FocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 1.0;
        jPanel51.add(jTextField9, gridBagConstraints);

        jCheckBox1.setText("Tick if Document is Availed");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 1.0;
        jPanel51.add(jCheckBox1, gridBagConstraints);

        jLabel55.setForeground(new java.awt.Color(0, 0, 0));
        jLabel55.setText("jLabel55");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        jPanel51.add(jLabel55, gridBagConstraints);

        jLabel57.setForeground(new java.awt.Color(255, 51, 51));
        jLabel57.setText("jLabel57");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        jPanel51.add(jLabel57, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel51.add(datePicker5, gridBagConstraints);

        jLabel22.setText("First Date of Delivery");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        jPanel51.add(jLabel22, gridBagConstraints);

        jLabel23.setText("Contract Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        jPanel51.add(jLabel23, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel51.add(datePicker6, gridBagConstraints);

        jLabel24.setText("Delivery Phases");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        jPanel51.add(jLabel24, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel51.add(jSpinner1, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("check InterNalFrame Opened()");
        jPanel51.add(jLabel2, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        contract_management.add(jPanel51, gridBagConstraints);

        jPanel55.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));
        jPanel55.setLayout(new java.awt.GridBagLayout());

        jButton24.setText("Save Data");
        jButton24.setEnabled(false);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel55.add(jButton24, gridBagConstraints);

        jButton25.setText("Edit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel55.add(jButton25, gridBagConstraints);

        jButton26.setText("Help");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel55.add(jButton26, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        contract_management.add(jPanel55, gridBagConstraints);

        jTabbedPane3.addTab("Contract Management", contract_management);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jTabbedPane3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel4, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void syncItemList(String refName){


        try {
            
            PreparedStatement itemsync = connectDB.prepareStatement("SELECT  DISTINCT item_code, item_description,units, quantity TENDER_QTY from st_item_to_quote   WHERE tender_no = '"+refName+"'  and quantity_ordered=0 order by 1");
            
            ResultSet workSync = itemsync.executeQuery();
            int i =0;
            while(workSync.next()){
            

                
            itemTbl.setValueAt(false, i, 0);
            itemTbl.setValueAt(workSync.getObject(1), i, 1);
            itemTbl.setValueAt(workSync.getObject(2), i, 2);
            itemTbl.setValueAt(workSync.getObject(3), i, 3);
            itemTbl.setValueAt(workSync.getObject(4), i, 4);
            
            
  
          i++;
         }    
            
     } 
        
        catch (SQLException ex) {
            Logger.getLogger(SSOFInancialEvaluationIntfr.class.getName()).log(Level.SEVERE, null, ex);
        }













}
    private void sortCmbxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sortCmbxItemStateChanged
        // TODO add your handling code here:

//        if(sortCmbx.getSelectedIndex()==1)
//        {
//            //select distinct supplier_code, FALSE AWARD from st_technical_evaluation  where  quotation_no 
//            biddersTbl.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectors(connectDB, "b.supplier_code, FALSE AWARD , a.sum(quantity*unit_price) Total_Amt FROM st_floated_quotations a,  st_technical_evaluation b "
//                    + " where ordered =false and quotation_no ilike '"+tenderNoTxt.getText().toString()+"' group by supplier order by 3 asc"));
//            biddersTbl.setShowHorizontalLines(false);
//            jScrollPane5.setViewportView(biddersTbl);
////            jLabel45.setText(null);
//        }
//        else if(sortCmbx.getSelectedIndex()==2){
//            biddersTbl.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectors(connectDB, "SELECT  distinct supplier, false Award, sum(quantity*unit_price) Total_Amt FROM st_floated_quotations  where ordered =false and quotation_no ilike'"+tenderNoTxt.getText().toString()+"' group by supplier order by 3 desc"));
//            biddersTbl.setShowHorizontalLines(false);
//            jScrollPane5.setViewportView(biddersTbl);
//        //    jLabel45.setText(null);
//        }
//        else{
//
//            biddersTbl.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectors(connectDB, "SELECT  distinct supplier, false award FROM st_floated_quotations  where ordered =false and quotation_no ilike'"+tenderNoTxt.getText().toString()+"';"));
//            biddersTbl.setShowHorizontalLines(false);
//            jScrollPane5.setViewportView(biddersTbl);
//
//        }

    }//GEN-LAST:event_sortCmbxItemStateChanged
    private void searchtendertoaward(){
        
        java.awt.Point point = this.tenderNoTxt.getLocationOnScreen();
        searchtender3.setSize(400, 200);
        searchtender3.setLocation(point);
        searchtender3.setVisible(true);
    }
    private void searchButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton5ActionPerformed
        // searchButton13Clicked();
        searchtendertoaward();       // TODO add your handling code here:
        
    }//GEN-LAST:event_searchButton5ActionPerformed
//l`  gbhn9 m0,p----------------------------------------------------------------------------------------------------
    private java.lang.String getBidderName(java.lang.String bidderCode){
        String name= null;
        try {
            java.sql.Statement cd = connectDB.createStatement();
               
                    ResultSet cditm = cd.executeQuery("SELECT distinct bidder FROM st_bidder_code where quotation_no = '"+tenderNoTxt.getText().toString()+"' and bidder_no='"+bidderCode+"' ;");
                    
                    

                      while(cditm.next()){
                    
                         name = cditm.getObject(1).toString();
                         System.out.println(name);
                         
                       }
        } catch (SQLException ex) {
            Logger.getLogger(SSOFInancialEvaluationIntfr.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        return name;
    
    
    }
    
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        java.awt.Point p = jTextField3.getLocationOnScreen();
        searchtenderc.setSize(400, 200);
        searchtenderc.setLocation(p);
        searchtenderc.setVisible(true);

    }//GEN-LAST:event_jButton22ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        java.awt.Point p = jTextField6.getLocationOnScreen();
        searchsupplierc.setSize(400, 200);
        searchsupplierc.setLocation(p);
        searchsupplierc.setVisible(true);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jTextField9CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField9CaretUpdate
        //        // TODO add your handling code here:
        //        if(jTextField9.getCaretPosition()==0){
            //
            //           jLabel57.setVisible(false);
            //        }
        //        else{
            //            try{
                //        java.sql.PreparedStatement f = connectDB.prepareStatement("SELECT replace(cash_words('"+jTextField9.getText()+"'::money),'dollars','Kenya Shillings')");
                //        ResultSet t = f.executeQuery();
                //        while (t.next()){
                    //            jLabel57.setVisible(true);
                    //            jLabel57.setText(t.getObject(1).toString());
                    //
                    //        }
                //
                //        }
            //        catch(Exception d){
                //        d.printStackTrace();
                //        }
            //
            //
            //
            //        }
    }//GEN-LAST:event_jTextField9CaretUpdate

    private void jTextField9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusLost
        // TODO add your handling code here:
        if(jTextField9.getText().length()==0){
            Double b= Double.parseDouble(jTextField9.getText().toString());
            jTextField9.setText("Kshs  "+com.afrisoftech.lib.CurrencyFormatter.getFormattedDouble(b).toString());

        }
    }//GEN-LAST:event_jTextField9FocusLost

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()){
            jButton24.setEnabled(true);
        }
        else{
            jButton24.setEnabled(false);
        }

    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        try {
            // TODO add your handling code here:
            connectDB.setAutoCommit(false);

            java.sql.PreparedStatement save = connectDB.prepareStatement("INSERT INTO st_contract_mgt(tender_no, supplier, item_desc, quantity, units, delivery_phases)"
                + " VALUES (?, ?, ?, ?, ?, ?);");

            for (int i=0;i<jTable5.getModel().getRowCount();i++){
                if(jTable5.getModel().getValueAt(i, 0)!=null){
                    save.setObject(1, jTextField3.getText().toString());
                    save.setObject(2, jTextField6.getText().toString());
                    save.setObject(3, jTable5.getModel().getValueAt(i, 0));
                    save.setObject(4, jTable5.getModel().getValueAt(i, 1));
                    save.setObject(5, jTable5.getModel().getValueAt(i, 2));
                    save.setObject(6, jTable5.getModel().getValueAt(i, 3));
                    //save.setObject(7, "");

                    save.executeUpdate();
                }
            }

            java.sql.PreparedStatement save2 = connectDB.prepareStatement("UPDATE st_floated_quotation_docs SET performance_bond= '"+jTextField9.getText().toString()+"' WHERE supplier_name='"+jTextField6.getText().toString()+"' and tender_no='"+jTextField3.getText().toString()+"'");

            save2.executeUpdate();

            connectDB.commit();
            javax.swing.JOptionPane.showMessageDialog(this, "Insert Successful");

        }

        catch (SQLException ex) {
            ex.printStackTrace();
            try {
                connectDB.rollback();
            } catch (SQLException ex1) {
                ex1.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton24ActionPerformed

    private void tenderrecordstxt3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tenderrecordstxt3CaretUpdate
        // TODO add your handling code here:
        if (this.tenderrecordstxt3.getCaretPosition() > 4) {
            System.out.print("Nothing");
//
//        } else
//
//        {
            //tenderrecordstbl3.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectorsCaret(connectDB, "SELECT distinct a.quotation_no from st_technical_evaluation a,st_floated_quotations b where a.quotation_no= b.quotation_no and b.ordered=false and a.total_mark='100' and a.quotation_no ILIKE '%" + tenderrecordstxt3.getText() + "%' "));
            tenderrecordstbl3.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectorsCaret(connectDB, "SELECT DISTINCT quotation_no FROM st_technical_evaluation  WHERE quotation_no ILIKE '%" + tenderrecordstxt3.getText() + "%' " ));
            //tenderrecordstbl3.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectorsCaret(connectDB, "SELECT DISTINCT quotation_no FROM st_technical_evaluation  WHERE quotation_no ILIKE '%" + tenderrecordstxt3.getText() + "%'  AND quotation_no NOT IN( SELECT distinct quotation_no FROM st_recommendation WHERE agenda_approval=true) "));
            tenderrecordstbl3.setShowHorizontalLines(false);

            tenderrecordsspnl3.setViewportView( tenderrecordstbl3);

            //            int n=0, m=0;
            //            if(tenderrecordstbl3.getValueAt(n, m)==null){
                //            java.awt.Point p = tenderrecordsspnl3.getLocationOnScreen();
                //            jLabel9.setVisible(true);
                //            jLabel9.setLocation(p);
                //            }

        }

    }//GEN-LAST:event_tenderrecordstxt3CaretUpdate

    private void tenderrecordstxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenderrecordstxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenderrecordstxt3ActionPerformed

    private void tenderrecordstbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenderrecordstbl3MouseClicked
        // TODO add your handling code here:
         this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        tenderNoTxt.setText(tenderrecordstbl3.getValueAt(tenderrecordstbl3.getSelectedRow(), 0).toString());

            searchtender3.dispose();
            
            
            syncItemList(tenderNoTxt.getText());
       
 this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    }//GEN-LAST:event_tenderrecordstbl3MouseClicked

    private void closebtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtn8ActionPerformed
        // TODO add your handling code here:
        searchtender3.dispose();
    }//GEN-LAST:event_closebtn8ActionPerformed

    private void tenderrecordstxt4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tenderrecordstxt4CaretUpdate
        // TODO add your handling code here
        if(tenderrecordstxt4.getCaretPosition()<1){
            System.out.println("nice");
        }
        else{
            tenderrecordstbl4.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectors(connectDB, "SELECT DISTINCT quotation_no FROM st_orders WHERE quotation_no ILIKE '" + tenderrecordstxt4.getText().toString() + "%' and ordered=false  ORDER BY 1"));
            tenderrecordstbl4.setShowHorizontalLines(true);
            tenderrecordsspnl4.setViewportView(tenderrecordstbl4);

        }
    }//GEN-LAST:event_tenderrecordstxt4CaretUpdate

    private void tenderrecordstxt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenderrecordstxt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenderrecordstxt4ActionPerformed

    private void tenderrecordstbl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenderrecordstbl4MouseClicked
        // TODO add your handling code here:
        jLabel55.setText(null);
        jTextField3.setText(tenderrecordstbl4.getModel().getValueAt(tenderrecordstbl4.getSelectedRow(), 0).toString());
        searchsupplierstbl5.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectors(connectDB, "select distinct supplier, quotation_no , sum(quantity*unit_price)::integer from st_orders where quotation_no = '"+jTextField3.getText().toString()+"'  AND ordered = false group by 1,2  "));
        this.searchtenderc.dispose();

    }//GEN-LAST:event_tenderrecordstbl4MouseClicked

    private void closebtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtn10ActionPerformed
        // TODO add your handling code here:
        this.searchtenderc.dispose();
    }//GEN-LAST:event_closebtn10ActionPerformed

    private void searchtendercFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchtendercFocusLost
        // TODO add your handling code here:
        this.searchtenderc.dispose();
    }//GEN-LAST:event_searchtendercFocusLost

    private void searchsuppliertxt5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_searchsuppliertxt5CaretUpdate
        // TODO add your handling code here:
        searchsupplierstbl5.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectors(connectDB, "select distinct supplier, quotation_no, sum(quantity*gross_value)::integer from st_orders where quotation_no = '"+jTextField3.getText().toString()+"'  AND ordered = false group by 1,2 "));
    }//GEN-LAST:event_searchsuppliertxt5CaretUpdate

    private void searchsuppliertxt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchsuppliertxt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchsuppliertxt5ActionPerformed

    private void searchsupplierstbl5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchsupplierstbl5MouseClicked
        // TODO add your handling code here:
        jTextField6.setText(searchsupplierstbl5.getModel().getValueAt(searchsupplierstbl5.getSelectedRow(), 0).toString());
        //select item ITEM_DESC,units,quantity,unit_price,sum(quantity*unit_price) Total_Price,''DELIVERY_PHASES,''FIRST_DELIVERY_DATE from st_orders where quotation_no= 'KNH/TNo124-2013/2014' and supplier='PRODIGY PHARMACEUTICALS  LIMITED' group by 1,2,3,4    '"+jTextField3.getText()+"' '"+jTextField6.getText()+"'
        jTable5.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectors(connectDB, "select item ITEM_DESC,units,quantity,unit_price,sum(quantity*unit_price) Total_Price from st_orders where quotation_no= '"+jTextField3.getText()+"' and supplier='"+jTextField6.getText()+"' group by 1,2,3,4 "));

        jTextField7.setText(searchsupplierstbl5.getModel().getValueAt(searchsupplierstbl5.getSelectedRow(), 2).toString());

        if(jTextField7.getText().length()>0){

            Double a = Double.parseDouble(jTextField7.getText().toString());
            try{
                java.sql.PreparedStatement s = connectDB.prepareStatement("SELECT replace(cash_words('"+jTextField7.getText()+"'::money),'dollars','Kenya Shillings')");
                ResultSet t = s.executeQuery();
                while (t.next()){
                    jLabel55.setVisible(true);
                    jLabel55.setText(t.getObject(1).toString());

                }

            }
            catch(Exception g){
                g.printStackTrace();
            }

            Double b = (a*0.05);

            try{
                java.sql.PreparedStatement f = connectDB.prepareStatement("SELECT replace(cash_words('"+b+"'::money),'dollars','Kenya Shillings')");
                ResultSet t = f.executeQuery();
                while (t.next()){
                    jLabel57.setVisible(true);
                    jLabel57.setText(t.getObject(1).toString());

                }

            }
            catch(Exception d){
                d.printStackTrace();
            }

            // com.afrisoftech.lib.CurrencyFormatter.getFormattedDouble(b);

            jTextField9.setText("Kshs  "+com.afrisoftech.lib.CurrencyFormatter.getFormattedDouble(b).toString());
        }
        else{
            jTextField9.setText("");
        }

        this.searchsupplierc.dispose();
        //
    }//GEN-LAST:event_searchsupplierstbl5MouseClicked

    private void closebtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtn11ActionPerformed
        // TODO add your handling code here:
        this.searchsupplierc.dispose();
    }//GEN-LAST:event_closebtn11ActionPerformed

    private void searchsuppliercFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchsuppliercFocusLost
        // TODO add your handling code here:
        this.searchsupplierc.dispose();
    }//GEN-LAST:event_searchsuppliercFocusLost

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        JPanel MainPanellToLoad=new JPanel();
        jSplitPane1.setDividerLocation(400);
        MainPanellToLoad = (JPanel) new ContractPanel(connectDB,null);
        //KickOlson.setVisible(true);
        contract_management.removeAll();
        contract_management.setLayout(new java.awt.BorderLayout());
        contract_management.add(MainPanellToLoad, java.awt.BorderLayout.CENTER);
        contract_management.updateUI();
        
        System.out.println("Sorry Olson");
        
       
    }//GEN-LAST:event_formInternalFrameOpened

    private void itemTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTblMouseClicked
        // TODO add your handling code here:
   for(int i=0;i<itemTbl.getRowCount();i++){ 
        
        if(i!=itemTbl.getSelectedRow()){
  
         itemTbl.setValueAt(false, i, 0);
        }
               
   }
        
        
        if(itemTbl.getValueAt(itemTbl.getSelectedRow(), 1)!=null && itemTbl.getValueAt(itemTbl.getSelectedRow(), 0)==java.lang.Boolean.TRUE ){
        //jLabel5.setText("Item Selected: ["+itemTbl.getValueAt(itemTbl.getSelectedRow(),1).toString()+"] ["+itemTbl.getValueAt(itemTbl.getSelectedRow(),2).toString()+"]");
        super.setTitle("Item Selected: ["+itemTbl.getValueAt(itemTbl.getSelectedRow(),1).toString()+"] ["+itemTbl.getValueAt(itemTbl.getSelectedRow(),2).toString()+"]");
        
        System.out.println("Item Selected: ["+itemTbl.getValueAt(itemTbl.getSelectedRow(),1).toString()+"] ["+itemTbl.getValueAt(itemTbl.getSelectedRow(),2).toString()+"]");
        
//      itemsQuotedTbl.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectors(connectDB, "SELECT supplier_code BIDDER,quantity,price UNIT_PRICE,(quantity*price) TOTAL_VALUE, FALSE AWARD , '-' REMARKS FROM st_recommendation WHERE quotation_no='"+tenderNoTxt.getText()+"' AND agenda_no='"+agendaTxt.getText()+"' AND description ilike '"+itemTbl.getValueAt(itemTbl.getSelectedRow(), 2)+"' AND financial_approved=false"));
     
       resetEvalTbl();
       totalSelected.setText("0.00");
       sort1btn.setEnabled(true);
       sort2btn.setEnabled(true);
       
        }
        else{
            if( itemTbl.getValueAt(itemTbl.getSelectedRow(), 0)==java.lang.Boolean.TRUE ){
                jLabel5.setText("-");
                JOptionPane.showMessageDialog(this , "No Item To Evaluate");
                ClearTable.clearthisTable(itemsQuotedTbl);
               
        for(int i=0;i<itemTbl.getRowCount();i++){ 
        
       itemTbl.setValueAt(false, i, 0);
        totalSelected.setText("0.00");
           
   }
                
                
                
                
                
            }
        }
    }//GEN-LAST:event_itemTblMouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
      //com.afrisoftech.hospital.HospitalMain.mainSplitPane.setDividerLocation(0);
         this.setSize(StockMain.medicdspane.getSize());
    }//GEN-LAST:event_formInternalFrameActivated
     private void resetEvalTbl(){
    int rowCount =0;
    ClearTable.clearthisTable(itemsQuotedTbl);
    itemsQuotedTbl.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectors(connectDB,"select distinct supplier_code BIDDER, '' quantity,''UNIT_PRICE,'' TOTAL_VALUE,FALSE AWARD , '-' REMARKS from st_technical_evaluation WHERE quotation_no='"+tenderNoTxt.getText()+"' and item_desc ilike '"+itemTbl.getValueAt(itemTbl.getSelectedRow(), 2)+"' AND total_mark >=passmark and approved= false and item_desc NOT IN(select distinct description from st_recommendation where quotation_no='"+tenderNoTxt.getText()+"') "));
            try {
                //Get quantity, unit price, total value
                
                for(int i=0; i<itemsQuotedTbl.getRowCount(); i++){
                    System.out.println(itemTbl.getValueAt(itemTbl.getSelectedRow(), 2)+"---> "+getBidderName(itemsQuotedTbl.getValueAt(i, 0).toString()));  
                PreparedStatement getQuoted =  connectDB.prepareStatement("SELECT quantity,unit_price,(quantity*unit_price) FROM st_floated_quotations WHERE supplier ILIKE '"+getBidderName(itemsQuotedTbl.getValueAt(i, 0).toString())+"' AND quotation_no='"+tenderNoTxt.getText()+"' AND item_description ILIKE '"+itemTbl.getValueAt(itemTbl.getSelectedRow(), 2)+"'");
                ResultSet rset = getQuoted.executeQuery();
                while(rset.next()){
                
                  itemsQuotedTbl.setValueAt((rset.getDouble(1)), i, 1);
                  itemsQuotedTbl.setValueAt(rset.getDouble(2), i, 2);
                  itemsQuotedTbl.setValueAt(rset.getDouble(3), i, 3);
  
                }
      
           }
                
                
                
                
                
            } catch (SQLException ex) {
                ex.printStackTrace();
                Logger.getLogger(SSOFInancialEvaluationIntfr.class.getName()).log(Level.SEVERE, null, ex);
            }
            
    rowCount = itemsQuotedTbl.getRowCount();
        System.out.println(rowCount);
        
        if(rowCount<1){
              itemsQuotedTbl.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectors(connectDB, "SELECT supplier_code BIDDER,quantity,price UNIT_PRICE,(quantity*price) TOTAL_VALUE, FALSE AWARD , '-' REMARKS FROM st_recommendation WHERE quotation_no='"+tenderNoTxt.getText()+"'  AND description ilike '"+itemTbl.getValueAt(itemTbl.getSelectedRow(), 2)+"' AND financial_approved=false AND quantity>0" ));
   
        }
    
    
    
    
    }
    private void itemsQuotedTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsQuotedTblMouseClicked
        // TODO add your handling code here:
         double total=0.0;
         
//if(itemsQuotedTbl.getSelectedColumn()==4){   
       
 
    if( Boolean.valueOf(itemsQuotedTbl.getModel().getValueAt(itemsQuotedTbl.getSelectedRow(), 4).toString())==java.lang.Boolean.TRUE){
       

        total= Double.valueOf(itemsQuotedTbl.getModel().getValueAt(itemsQuotedTbl.getSelectedRow(), 1).toString());
        
      totalSelected.setText(CurrencyFormatter.getFormattedDouble(total+Double.valueOf(totalSelected.getText().replace(",",""))));

      
      
      
      
      if(Double.valueOf(totalSelected.getText().replace(",","").toString())>Double.valueOf(itemTbl.getValueAt(itemTbl.getSelectedRow(), 4).toString())){
          
          
          
          JOptionPane.showMessageDialog(this, "Quantity Exceeded, Resetting Table");
      
         // itemsQuotedTbl.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectors(connectDB, "SELECT supplier_code BIDDER,quantity,price UNIT_PRICE,(quantity*price) TOTAL_VALUE,FALSE AWARD FROM st_recommendation WHERE quotation_no='"+tenderNoTxt.getText()+"' AND agenda_no='"+agendaTxt.getText()+"' AND description ilike '"+itemTbl.getValueAt(itemTbl.getSelectedRow(), 2)+"' AND financial_approved=false"));
          
          //Resetting Table 
      resetEvalTbl();
            
            
      totalSelected.setText("0.00");

         }
     //}

        
                
}           
    }//GEN-LAST:event_itemsQuotedTblMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int exitOption = javax.swing.JOptionPane.showConfirmDialog(this, "You are Recommending " + itemTbl.getValueAt(itemTbl.getSelectedRow(), 2) + "  to Selected Bidder(s) \n You CANNOT Reverse This Action. Continue ?", "Caution before Saving!", javax.swing.JOptionPane.YES_NO_CANCEL_OPTION);

        if (exitOption == javax.swing.JOptionPane.YES_OPTION) {   
        sort1btn.setEnabled(false);
        sort2btn.setEnabled(false);
try {
          
    double award_quantity; 
    award_quantity = Double.valueOf(totalSelected.getText().replace(",",""));
if(award_quantity <= Double.valueOf(itemTbl.getValueAt(itemTbl.getSelectedRow(), 4).toString())){
    System.out.println(award_quantity);
    
  for(int i= 0;i<itemsQuotedTbl.getRowCount();i++){
      
    if( itemsQuotedTbl.getModel().getValueAt(i, 4)==java.lang.Boolean.TRUE){
        
   
           
       System.out.println("We are starting to Insert Information in st_recommendation..."+getBidderName(itemsQuotedTbl.getModel().getValueAt(i, 0).toString()));
      
        
             
             System.out.println("This"+award_quantity);
             
           
             java.sql.PreparedStatement update_code = connectDB.prepareStatement("INSERT INTO st_recommendation( supplier,  quotation_no, item_code, description, unit, price, user_name, quantity, supplier_code, remarks, financial_approved,approved_fin_by,financial_date)\n" +
"    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?); ");
              
  
  
                     update_code.setObject(1, getBidderName(itemsQuotedTbl.getModel().getValueAt(i, 0).toString()).toUpperCase());
                     update_code.setObject(2, tenderNoTxt.getText());
                     update_code.setObject(3, itemTbl.getValueAt(itemTbl.getSelectedRow(), 1));
                     update_code.setObject(4, itemTbl.getValueAt(itemTbl.getSelectedRow(), 2));
                     update_code.setObject(5, itemTbl.getValueAt(itemTbl.getSelectedRow(), 3));
                     update_code.setObject(6, itemsQuotedTbl.getValueAt(i, 2));
                     update_code.setObject(7, com.afrisoftech.lib.UserName.getLoginName(connectDB).toLowerCase());
                     update_code.setObject(8, itemsQuotedTbl.getValueAt(i, 1));
                     update_code.setObject(9, itemsQuotedTbl.getModel().getValueAt(i, 0));
                     update_code.setObject(10, itemsQuotedTbl.getModel().getValueAt(i, 5));
                     update_code.setObject(11, true);
                     update_code.setObject(12, com.afrisoftech.lib.UserName.getLoginName(connectDB).toLowerCase());
                     update_code.setObject(13, com.afrisoftech.lib.UserName.getServerDate(connectDB));
                     
                     
                     
                     update_code.executeUpdate();
                     
                     
                     
               java.sql.PreparedStatement update_tech = connectDB.prepareStatement("UPDATE st_technical_evaluation SET approved=true where quotation_no='"+tenderNoTxt.getText()+"' AND supplier ILIKE '"+getBidderName(itemsQuotedTbl.getModel().getValueAt(i, 0).toString())+"' "
                       + "AND item_desc ilike '"+itemTbl.getValueAt(itemTbl.getSelectedRow(), 2)+"'");
               update_tech.executeUpdate();
                     
               
               
                javax.swing.JOptionPane.showMessageDialog(this, "Bidder Evaluated Successfully");
               
               // ItemListSync(tenderNoTxt.getText(), supp);
                //jButton4.doClick(); 
              
                     
                 
                 connectDB.commit();
                 
          
    
  
              }
    
          }
  
        
                ///tracking  

           java.sql.Statement stmtss = connectDB.createStatement();
           java.sql.ResultSet resd=stmtss.executeQuery("SELECT distinct evaluation FROM st_pr_progress  WHERE approved_by_tc='"+tenderNoTxt.getText()+"'"  );
           while(resd.next()){
           
           evaluation_dtls=resd.getString(1)+"-"+com.afrisoftech.lib.UserName.getLoginName(connectDB).toLowerCase()+"-FIN-"+com.afrisoftech.lib.UserName.getServerDate(connectDB);
           
    
          
           
           }
               TenderTrack.TrackTable(connectDB, "evaluation", evaluation_dtls , tenderNoTxt.getText());

               connectDB.commit();
               javax.swing.JOptionPane.showMessageDialog(this, "Item Recommended Succesfully ");
    //           syncItemList(name);
                  ClearTable.clearthisTable(itemsQuotedTbl);
      }
             else{
             
             
             javax.swing.JOptionPane.showMessageDialog(this, "You Cant award More Than The Tender Quantity");
             
             }
 }
          catch (SQLException ex) {
              ex.printStackTrace();
            try {
                connectDB.rollback();
                 } 
            
            catch (SQLException ex1) {
                Logger.getLogger(SSOFInancialEvaluationIntfr.class.getName()).log(Level.SEVERE, null, ex1);
            }
          }
       }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void thresholdspinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_thresholdspinnerStateChanged
        // TODO add your handling code here:
        
        
        resetEvalTbl();
        
        
        
        
    }//GEN-LAST:event_thresholdspinnerStateChanged

    private void prelRptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prelRptbtnActionPerformed
        // TODO add your handling code here:
         if(tenderNoTxt.getText().length()<1){
        javax.swing.JOptionPane.showMessageDialog(this, "Select Tender Number First");
        }
        else{
        //javax.swing.JOptionPane.showMessageDialog(this, "Work In Progress...");
            TenderPreliminaryReportPDF policy = new TenderPreliminaryReportPDF();
            policy.TenderPreliminaryReportPDF(connectDB, tenderNoTxt.getText());
            
          
        }
           
    }//GEN-LAST:event_prelRptbtnActionPerformed

    private void techrptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_techrptbtnActionPerformed
        // TODO add your handling code here:
         if(tenderNoTxt.getText().length()<1){
        javax.swing.JOptionPane.showMessageDialog(this, "Select Tender Number First");
        }
        else{
        //javax.swing.JOptionPane.showMessageDialog(this, "Work In Progress...");
 
            TenderTechnicalReportPDF policy = new TenderTechnicalReportPDF();
            policy.TenderTechnicalReportPDF(connectDB, tenderNoTxt.getText());
        
        }
    }//GEN-LAST:event_techrptbtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
         if(tenderNoTxt.getText().length()<1){
        javax.swing.JOptionPane.showMessageDialog(this, "Select Tender Number First");
        }
        else{
        //javax.swing.JOptionPane.showMessageDialog(this, "Work In Progress...");
 
              com.afrisoftech.hospinventory.mtrhreports.TenderEvaluationSummaryPDF policy = new  com.afrisoftech.hospinventory.mtrhreports.TenderEvaluationSummaryPDF();
              policy.TenderEvaluationSummaryPDF(connectDB, tenderNoTxt.getText());
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sort1btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort1btnActionPerformed
        // TODO add your handling code here:
        
        itemsQuotedTbl.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectors(connectDB,"select distinct a.supplier_code BIDDER, b.quantity,b.unit_price UNIT_PRICE,b.quantity*b.unit_price TOTAL_VALUE,FALSE AWARD , '-' REMARKS from st_technical_evaluation a, st_floated_quotations b WHERE a.quotation_no='"+tenderNoTxt.getText()+"' and a.item_desc ilike '"+itemTbl.getValueAt(itemTbl.getSelectedRow(), 2)+"' AND a.total_mark >=a.passmark and a.approved= false and a.item_desc NOT IN(select distinct description from st_recommendation where quotation_no='"+tenderNoTxt.getText()+"') and a.supplier=b.supplier  and a.item_desc=b.item_description group by 1,2,3,5,6 order by  b.unit_price asc"));
        
    }//GEN-LAST:event_sort1btnActionPerformed

    private void sort2btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort2btnActionPerformed
        // TODO add your handling code here:
        
         itemsQuotedTbl.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectors(connectDB,"select distinct a.supplier_code BIDDER, b.quantity,b.unit_price UNIT_PRICE,b.quantity*b.unit_price TOTAL_VALUE,FALSE AWARD , '-' REMARKS from st_technical_evaluation a, st_floated_quotations b WHERE a.quotation_no='"+tenderNoTxt.getText()+"' and a.item_desc ilike '"+itemTbl.getValueAt(itemTbl.getSelectedRow(), 2)+"' AND a.total_mark >=a.passmark and a.approved= false and a.item_desc NOT IN(select distinct description from st_recommendation where quotation_no='"+tenderNoTxt.getText()+"') and a.supplier=b.supplier  and a.item_desc=b.item_description group by 1,2,3,5,6 order by  b.unit_price desc"));
    }//GEN-LAST:event_sort2btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agendaTxt;
    private javax.swing.JButton closebtn10;
    private javax.swing.JButton closebtn11;
    private javax.swing.JButton closebtn8;
    private javax.swing.JPanel contract_management;
    private com.afrisoftech.lib.DatePicker datePicker5;
    private com.afrisoftech.lib.DatePicker datePicker6;
    private javax.swing.JTextField finYrTxt;
    private javax.swing.JPanel financialEvaluation;
    private javax.swing.JTable itemTbl;
    private javax.swing.JTable itemsQuotedTbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton prelRptbtn;
    private javax.swing.JButton searchButton5;
    private javax.swing.JDialog searchsupplierc;
    private javax.swing.JPanel searchsupplierpnl5;
    private javax.swing.JScrollPane searchsupplierspnl5;
    private javax.swing.JTable searchsupplierstbl5;
    private javax.swing.JTextField searchsuppliertxt5;
    private javax.swing.JDialog searchtender3;
    private javax.swing.JDialog searchtenderc;
    private javax.swing.JButton sort1btn;
    private javax.swing.JButton sort2btn;
    private javax.swing.JComboBox sortCmbx;
    private javax.swing.ButtonGroup tableBtnGroup;
    private javax.swing.JButton techrptbtn;
    private javax.swing.JTextField tenderNoTxt;
    private javax.swing.JPanel tenderrecordspnl3;
    private javax.swing.JPanel tenderrecordspnl4;
    private javax.swing.JScrollPane tenderrecordsspnl3;
    private javax.swing.JScrollPane tenderrecordsspnl4;
    private javax.swing.JTable tenderrecordstbl3;
    private javax.swing.JTable tenderrecordstbl4;
    private javax.swing.JTextField tenderrecordstxt3;
    private javax.swing.JTextField tenderrecordstxt4;
    private javax.swing.JSpinner thresholdspinner;
    private javax.swing.JTextField totalSelected;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
