/*
 * test.java
 *
 * Created on August 9, 2006, 11:18 AM
 */

package com.afrisoftech.fleet.fleetdoc;

/**
 *
 * @author  root
 */
public class test extends javax.swing.JInternalFrame {
    
    /** Creates new form test */
    public test() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
        pack();
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
