/*
 * branchintfr.java
 *
 * Created on August 13, 2002, 10:14 AM
 */
package com.afrisoftech.accounting;

/**
 *
 * @author root
 */
public class Depreciationintfr extends javax.swing.JInternalFrame {

    java.sql.Connection connectDB = null;
    org.netbeans.lib.sql.pool.PooledConnectionSource pConnDB = null;

    public Depreciationintfr(java.sql.Connection connDb, org.netbeans.lib.sql.pool.PooledConnectionSource pconnDB) {

        connectDB = connDb;

        pConnDB = pconnDB;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        registerupdateBtn = new javax.swing.JButton();
        closeFormBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        depreciationAssetTypeCmbx = new javax.swing.JComboBox();
        depreciationRatesDetailsPanel = new javax.swing.JPanel();
        depreciationRatesJscrl = new javax.swing.JScrollPane();
        depreciationRatesTbl = new com.afrisoftech.dbadmin.JTable();
        depreciationGLCodeLbl = new javax.swing.JLabel();
        assetTypeGLCodeTxt = new javax.swing.JTextField();
        depreciationAccountGLLbl = new javax.swing.JLabel();
        depreciationChargeAccountCmbx = new javax.swing.JComboBox();
        depreciationChargeLbl = new javax.swing.JLabel();
        depreciationChargeGLCodeTxt = new javax.swing.JTextField();
        removeRowBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Depreciation Rates Setup ");
        setDoubleBuffered(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/ColorPreview.gif"))); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minusarm.gif"))); // NOI18N
        jButton1.setMnemonic('l');
        jButton1.setText("Clear");
        jButton1.setToolTipText("Click here to clear textfields");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jButton1, gridBagConstraints);

        registerupdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.gif"))); // NOI18N
        registerupdateBtn.setMnemonic('O');
        registerupdateBtn.setText("Register Depreciation rates");
        registerupdateBtn.setToolTipText("Click here to enter data");
        registerupdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerupdateBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(registerupdateBtn, gridBagConstraints);

        closeFormBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BD14755_.GIF"))); // NOI18N
        closeFormBtn.setMnemonic('C');
        closeFormBtn.setText("Close");
        closeFormBtn.setToolTipText("Click here to close window");
        closeFormBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFormBtnActionPerformed(evt);
            }
        });
        closeFormBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeFormBtnMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(closeFormBtn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jSeparator1, gridBagConstraints);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jLabel4, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter depreciation rate here"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Utopia", 0, 14)); // NOI18N
        jLabel3.setText("Asset Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jLabel3, gridBagConstraints);

        depreciationAssetTypeCmbx.setModel(com.afrisoftech.lib.ComboBoxModel.ComboBoxModel(connectDB, "select activity from pb_activity where activity ilike '%depreciation%' order by activity"));
        depreciationAssetTypeCmbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depreciationAssetTypeCmbxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(depreciationAssetTypeCmbx, gridBagConstraints);

        depreciationRatesDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        depreciationRatesDetailsPanel.setLayout(new java.awt.GridBagLayout());

        depreciationRatesTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Description", "Depreciation Rate(%)", "Investment Allowance(%)"
            }
        ));
        depreciationRatesTbl.setShowHorizontalLines(false);
        javax.swing.table.TableColumn column = null;
        for (int i = 0; i < 3; i++) {
            column = depreciationRatesTbl.getColumnModel().getColumn(i);
            if (i == 0) {

                column.setPreferredWidth(300); //sport column is bigger
            }  else {
                column.setPreferredWidth(100);

            }
        }
        depreciationRatesJscrl.setViewportView(depreciationRatesTbl);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        depreciationRatesDetailsPanel.add(depreciationRatesJscrl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 100.0;
        jPanel1.add(depreciationRatesDetailsPanel, gridBagConstraints);

        depreciationGLCodeLbl.setText("Gl Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(depreciationGLCodeLbl, gridBagConstraints);

        assetTypeGLCodeTxt.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(assetTypeGLCodeTxt, gridBagConstraints);

        depreciationAccountGLLbl.setText("Depreciation Category");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(depreciationAccountGLLbl, gridBagConstraints);

        depreciationChargeAccountCmbx.setModel(com.afrisoftech.lib.ComboBoxModel.ComboBoxModel(connectDB, "select upper(activity) as activity from pb_activity where activity ilike '%depreciation%' order by activity"));
        depreciationChargeAccountCmbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depreciationChargeAccountCmbxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(depreciationChargeAccountCmbx, gridBagConstraints);

        depreciationChargeLbl.setText("Depreciation Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(depreciationChargeLbl, gridBagConstraints);

        depreciationChargeGLCodeTxt.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(depreciationChargeGLCodeTxt, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        removeRowBtn.setMnemonic('r');
        removeRowBtn.setText("Remove Row");
        removeRowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRowBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(removeRowBtn, gridBagConstraints);

        editBtn.setText("Edit Deprection Rates");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(editBtn, gridBagConstraints);

        setBounds(0, 0, 795, 350);
    }// </editor-fold>//GEN-END:initComponents

    private void depreciationChargeAccountCmbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depreciationChargeAccountCmbxActionPerformed
        try {
            java.sql.Statement pst1 = connectDB.createStatement();
            java.sql.ResultSet rs1 = pst1.executeQuery("select code from pb_activity where activity ilike '" + depreciationChargeAccountCmbx.getSelectedItem().toString() + "'");
            while (rs1.next()) {
                depreciationChargeGLCodeTxt.setText(rs1.getString(1));
            }
        } catch (java.sql.SQLException sq) {
            sq.printStackTrace();
            System.out.println(sq.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, sq.getMessage(), "Error Message!", javax.swing.JOptionPane.ERROR_MESSAGE);


        }            // Add your handling code here:
    }//GEN-LAST:event_depreciationChargeAccountCmbxActionPerformed

    private void removeRowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRowBtnActionPerformed
        int rows2Delete = depreciationRatesTbl.getSelectedRowCount();

        int[] selectedRows = depreciationRatesTbl.getSelectedRows();

        if (rows2Delete < 1) {

            java.awt.Toolkit.getDefaultToolkit().beep();

            javax.swing.JOptionPane.showMessageDialog(this, "There are no selected rows to delete!");

        } else {

            if (rows2Delete > 1) {

                for (int i = 0; i < selectedRows.length; i++) {



                    javax.swing.table.DefaultTableModel defTableModel = (javax.swing.table.DefaultTableModel) depreciationRatesTbl.getModel();

                    defTableModel.removeRow(selectedRows[i]);

                }



            } else {

                javax.swing.table.DefaultTableModel defTableModel = (javax.swing.table.DefaultTableModel) depreciationRatesTbl.getModel();

                defTableModel.removeRow(depreciationRatesTbl.getSelectedRow());
            }
        }        // Add your handling code here:
    }//GEN-LAST:event_removeRowBtnActionPerformed

    private void depreciationAssetTypeCmbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depreciationAssetTypeCmbxActionPerformed
        try {
            java.sql.Statement pst1 = connectDB.createStatement();
            java.sql.ResultSet rs1 = pst1.executeQuery("select code from pb_activity where activity ilike '" + depreciationAssetTypeCmbx.getSelectedItem().toString() + "'");
            while (rs1.next()) {
                assetTypeGLCodeTxt.setText(rs1.getString(1));
            }
        } catch (java.sql.SQLException sq) {
            sq.printStackTrace();
            System.out.println(sq.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, sq.getMessage(), "Error Message!", javax.swing.JOptionPane.ERROR_MESSAGE);


        }      // Add your handling code here:
    }//GEN-LAST:event_depreciationAssetTypeCmbxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.assetTypeGLCodeTxt.setText("");
        this.depreciationAssetTypeCmbx.setSelectedItem(null);
        for (int k = 0; k < depreciationRatesTbl.getRowCount(); k++) {
            for (int r = 0; r < depreciationRatesTbl.getColumnCount(); r++) {
                depreciationRatesTbl.getModel().setValueAt(null, k, r);
            }
        }
        // Add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void closeFormBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFormBtnActionPerformed
        this.setVisible(false);// Add your handling code here:
    }//GEN-LAST:event_closeFormBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //try {
        this.getDesktopPane().setSelectedFrame(this);
        //}catch (java.beans.PropertyVetoException pr){
        //    System.out.println("Not Selected");
        //}
        // Add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void registerupdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerupdateBtnActionPerformed
        String accountCode = null;
        String TransNo = null;
        String glType = null;
        try {
            connectDB.setAutoCommit(false);
            for (int i = 0; i < depreciationRatesTbl.getRowCount(); i++) {
                if (registerupdateBtn.getText().equalsIgnoreCase("Register Depreciation rates")) {
                    if (depreciationRatesTbl.getModel().getValueAt(i, 1) != null) {
                        java.sql.PreparedStatement pstmt = connectDB.prepareStatement("insert into pb_depreciation_rates values(initcap(?),?, ?,?,?,?,?)");
                        pstmt.setString(1, depreciationAssetTypeCmbx.getSelectedItem().toString());
                        pstmt.setDouble(2, Double.parseDouble(depreciationRatesTbl.getValueAt(i, 1).toString()));
                        pstmt.setDate(3, com.afrisoftech.lib.ServerTime.getSQLDate(connectDB));
                        pstmt.setObject(4, depreciationRatesTbl.getValueAt(i, 0).toString());
                        pstmt.setString(5, assetTypeGLCodeTxt.getText());
                        pstmt.setDouble(6, Double.parseDouble(depreciationRatesTbl.getValueAt(i, 2).toString()));
                        pstmt.setString(7, depreciationChargeGLCodeTxt.getText());
                        pstmt.executeUpdate();
                        javax.swing.JOptionPane.showMessageDialog(this, "Depreciation Rates Registered Successfully", "Confirmation Message!", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                    }
                } else {
                    java.sql.PreparedStatement pstmtUpdate = connectDB.prepareStatement("UPDATE "
                            + "pb_depreciation_rates"
                            + "   SET asset_type= ?, rate= ?, date_set= ?, code = ?, investment_allowance= ?, "
                            + "       depreciation_code=? "
                            + " WHERE  name = ?");
                    pstmtUpdate.setString(1, depreciationRatesTbl.getValueAt(i, 1).toString());
                    pstmtUpdate.setDouble(2, Double.parseDouble(depreciationRatesTbl.getValueAt(i, 2).toString()));
                    pstmtUpdate.setDate(3, com.afrisoftech.lib.ServerTime.getSQLDate(connectDB));
                    pstmtUpdate.setString(4, depreciationRatesTbl.getValueAt(i, 4).toString());
                    pstmtUpdate.setDouble(5, Double.parseDouble(depreciationRatesTbl.getValueAt(i, 5).toString()));
                    pstmtUpdate.setString(6, depreciationRatesTbl.getValueAt(i, 7).toString());
                    pstmtUpdate.setObject(7, depreciationRatesTbl.getValueAt(i, 0).toString());
                    pstmtUpdate.executeUpdate();
                    javax.swing.JOptionPane.showMessageDialog(this, "Depreciation Rates Updated Successfully", "Confirmation Message!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    this.getContentPane().removeAll();
                    this.initComponents();
                    this.invalidate();
                    this.validate();
                }
                //}
            }

            connectDB.commit();
            connectDB.setAutoCommit(true);
            this.assetTypeGLCodeTxt.setText("");
            //   this.depreciationAssetTypeCmbx.setSelectedItem(null);
            jLabel4.setText("");
            this.registerupdateBtn.setText("Register Depreciation rates");

        } catch (java.sql.SQLException sq) {
            sq.printStackTrace();
            System.out.println(sq.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, sq.getMessage(), "Error Message!", javax.swing.JOptionPane.ERROR_MESSAGE);
            jLabel4.setForeground(java.awt.Color.red);
            jLabel4.setText("Sorry. Data not saved");
        }
        // Add your handling code here:
    }//GEN-LAST:event_registerupdateBtnActionPerformed

    private void closeFormBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeFormBtnMouseClicked
        // Add your handling code here:
    }//GEN-LAST:event_closeFormBtnMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // Add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed

        depreciationRatesTbl.setModel(com.afrisoftech.dbadmin.TableModel.createTableVectors(connectDB,
                "SELECT name as depreciation_type, asset_type as asset_depreciation_account, rate, date_set, code, investment_allowance, "
                + "       (SELECT activity FROM pb_activity WHERE pb_activity.code = pb_depreciation_rates.depreciation_code) as depreciation_charge_account, depreciation_code as depreciation_charge_code"
                + "  FROM pb_depreciation_rates"));

        javax.swing.JComboBox cmBox2 = new javax.swing.JComboBox(com.afrisoftech.lib.ComboBoxModel.ComboBoxModel(connectDB,
                "select activity from pb_activity where activity ilike "
                + "'%depreciation%' order by activity"));
        cmBox2.setEditable(false);

        javax.swing.table.TableColumn teditor2 = this.depreciationRatesTbl.getColumn("ASSET_DEPRECIATION_ACCOUNT");
        cmBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depreciationRatesTbl.setValueAt(com.afrisoftech.lib.GLCodesFactory.getGlCode(connectDB, depreciationRatesTbl.getValueAt(depreciationRatesTbl.getSelectedRow(), 1).toString()), depreciationRatesTbl.getSelectedRow(), 4);
            }
        });
        teditor2.setCellEditor(new javax.swing.DefaultCellEditor(cmBox2));

        javax.swing.JComboBox cmBox3 = new javax.swing.JComboBox(com.afrisoftech.lib.ComboBoxModel.ComboBoxModel(connectDB,
                "select activity from pb_activity where activity ilike "
                + "'%depreciation%' order by activity"));
        cmBox3.setEditable(false);
        
        javax.swing.table.TableColumn teditor3 = this.depreciationRatesTbl.getColumn("DEPRECIATION_CHARGE_ACCOUNT");

        cmBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depreciationRatesTbl.setValueAt(com.afrisoftech.lib.GLCodesFactory.getGlCode(connectDB, depreciationRatesTbl.getValueAt(depreciationRatesTbl.getSelectedRow(), 6).toString()), depreciationRatesTbl.getSelectedRow(), 7);
            }
        });
        teditor3.setCellEditor(new javax.swing.DefaultCellEditor(cmBox3));

        this.registerupdateBtn.setText("Update Depreciation rates");

        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assetTypeGLCodeTxt;
    private javax.swing.JButton closeFormBtn;
    private javax.swing.JLabel depreciationAccountGLLbl;
    private javax.swing.JComboBox depreciationAssetTypeCmbx;
    private javax.swing.JComboBox depreciationChargeAccountCmbx;
    private javax.swing.JTextField depreciationChargeGLCodeTxt;
    private javax.swing.JLabel depreciationChargeLbl;
    private javax.swing.JLabel depreciationGLCodeLbl;
    private javax.swing.JPanel depreciationRatesDetailsPanel;
    private javax.swing.JScrollPane depreciationRatesJscrl;
    private javax.swing.JTable depreciationRatesTbl;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton registerupdateBtn;
    private javax.swing.JButton removeRowBtn;
    // End of variables declaration//GEN-END:variables
}
