/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.afrisoftech.reports.emr;

/**
 *
 * @author Charles
 */
public class GISReporter extends javax.swing.JInternalFrame {

    /**
     * Creates new form GISReporter
     */
    java.sql.Connection connectDB = null;

    public GISReporter(java.sql.Connection connDB) {
        connectDB = connDB;
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) mapInternalFrame.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel10 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        datePicker3 = new com.afrisoftech.lib.DatePicker();
        datePicker5 = new com.afrisoftech.lib.DatePicker();
        refershGISReportBtn = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox();
        mapInternalFrame = new javax.swing.JInternalFrame();
        mapReportPanel1 = new com.roots.map.MapPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle(org.openide.util.NbBundle.getMessage(GISReporter.class, "GISReporter.title")); // NOI18N
        setVisible(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(GISReporter.class, "GISReporter.jPanel10.border.title"))); // NOI18N
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Attendance", "Morbidity", "Employee Distribution" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(GISReporter.class, "GISReporter.jComboBox1.border.title"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 5.0;
        gridBagConstraints.weighty = 1.0;
        jPanel10.add(jComboBox1, gridBagConstraints);

        datePicker3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(GISReporter.class, "GISReporter.datePicker3.border.title"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel10.add(datePicker3, gridBagConstraints);

        datePicker5.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(GISReporter.class, "GISReporter.datePicker5.border.title"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel10.add(datePicker5, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(refershGISReportBtn, org.openide.util.NbBundle.getMessage(GISReporter.class, "GISReporter.refershGISReportBtn.text")); // NOI18N
        refershGISReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refershGISReportBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel10.add(refershGISReportBtn, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jButton10, org.openide.util.NbBundle.getMessage(GISReporter.class, "GISReporter.jButton10.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel10.add(jButton10, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jButton11, org.openide.util.NbBundle.getMessage(GISReporter.class, "GISReporter.jButton11.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel10.add(jButton11, gridBagConstraints);

        jComboBox4.setModel(com.afrisoftech.lib.ComboBoxModel.ComboBoxModel(connectDB, "SELECT DISTINCT initcap(disease) FROM hp_patient_diagnosis")
        );
        jComboBox4.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(GISReporter.class, "GISReporter.jComboBox4.border.title"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 5.0;
        gridBagConstraints.weighty = 1.0;
        jPanel10.add(jComboBox4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel10, gridBagConstraints);

        mapInternalFrame.setVisible(true);
        mapInternalFrame.getContentPane().setLayout(new java.awt.GridBagLayout());

        mapReportPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(GISReporter.class, "GISReporter.mapReportPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 11), new java.awt.Color(102, 102, 255))); // NOI18N
        mapReportPanel1.setMapPosition(new java.awt.Point(9655, 8084));
        mapReportPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapReportPanel1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 100.0;
        mapInternalFrame.getContentPane().add(mapReportPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 100.0;
        getContentPane().add(mapInternalFrame, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refershGISReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refershGISReportBtnActionPerformed
        // mapFrame.set
        final com.roots.map.overlay.DemoGlassPane glassPane = new com.roots.map.overlay.DemoGlassPane(mapReportPanel1);

        glassPane.addPointToMark(new java.awt.Point.Double(37.30957, -1.29628));
        glassPane.addPointToMark(new java.awt.Point.Double(38.70957, 1.49628));
        glassPane.addPointToMark(new java.awt.Point.Double(36.30957, -2.29628));
        glassPane.addPointToMark(new java.awt.Point.Double(38.30957, -1.59628));
        glassPane.addPointToMark(new java.awt.Point.Double(32.30957, 0.59628));
        glassPane.addPointToMark(new java.awt.Point.Double(35.10957, -1.49628));
        glassPane.addPointToMark(new java.awt.Point.Double(36.30957, -0.29628));
        glassPane.addPointToMark(new java.awt.Point.Double(38.30957, 1.59628));
        glassPane.addPointToMark(new java.awt.Point.Double(39.00957, 5.29628));
        glassPane.addPointToMark(new java.awt.Point.Double(37.70957, -1.49628));
        glassPane.addPointToMark(new java.awt.Point.Double(36.30957, 2.29628));
        glassPane.addPointToMark(new java.awt.Point.Double(35.30957, 0.09628));
        glassPane.addPointToMark(new java.awt.Point.Double(37.30957, 1.79628));
        glassPane.addPointToMark(new java.awt.Point.Double(34.70957, 2.49628));
        glassPane.addPointToMark(new java.awt.Point.Double(36.30957, 2.29628));
        glassPane.addPointToMark(new java.awt.Point.Double(38.30957, -1.59628));
        glassPane.addPointToMark(new java.awt.Point.Double(35.30957, 3.29628));
        glassPane.addPointToMark(new java.awt.Point.Double(36.20957, 0.49628));
        glassPane.addPointToMark(new java.awt.Point.Double(34.30957, -0.29628));
        glassPane.addPointToMark(new java.awt.Point.Double(39.30957, -3.59628));

        mapInternalFrame.setGlassPane(glassPane);

        mapInternalFrame.getGlassPane().setVisible(true);

        this.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_refershGISReportBtnActionPerformed

    private void mapReportPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapReportPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mapReportPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.afrisoftech.lib.DatePicker datePicker3;
    private com.afrisoftech.lib.DatePicker datePicker5;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JInternalFrame mapInternalFrame;
    private com.roots.map.MapPanel mapReportPanel1;
    private javax.swing.JButton refershGISReportBtn;
    // End of variables declaration//GEN-END:variables
}
